In [5]:
print('c\\be')

c\be


In [ ]:
import torch

In [ ]:
x = [[[1, 2, 3, 4, 5 ],
     [0, 1, 2, 3, 4 ]],

      [[6, 7, 8, 9 , 10],
     [11, 12, 13, 14, 15]]
     ]

x = torch.Tensor(x)
threshold = 0.5
mask = torch.rand((2, 2, 1)) <= threshold
print(mask)



print(torch.mul(x, mask))

tensor([[[ True],
         [ True]],

        [[False],
         [False]]])
tensor([[[1., 2., 3., 4., 5.],
         [0., 1., 2., 3., 4.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [ ]:
temp_str = 'BÙi QuỐc HÙng Đa quẢ dỊch'
print(temp_str)
print(temp_str.lower())

BÙi QuỐc HÙng Đa quẢ dỊch
bùi quốc hùng đa quả dịch


In [ ]:
x = [[1, 2, 3],
     [4, 5, 6]]
result = []
for k in range(0, len(x[0])):
  temp = []
  for i in range(0, len(x)):
    temp.append(x[i][k])
  print(temp)
  result.append(temp)

print(result)

[1, 4]
[2, 5]
[3, 6]
[[1, 4], [2, 5], [3, 6]]


In [ ]:
import numpy as np

In [ ]:
left = np.zeros((10, 2))
right = np.ones((10, 3))
y_temp = np.zeros((10, 1))

In [ ]:
print(left)
print(right)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
zipped = zip(left, right)
print(zipped)
# print(list(zipped)) If you touch the zipped variable, even just temporary list-casting and printing it, the inside value will disappear

In [ ]:
left_t, right_t = zip(*zipped)

In [ ]:
print(np.array(left_t))
print(np.array(right_t))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
zipped_2 = zip(left, right)

In [ ]:
def split_zip(x, y, **params): # train_test_split params
  x = list(x)
  x_train, x_test, y_train, y_test = train_test_split(x, y, **params)
  print(x_train[0])

  x_train = zip([x_train[i][0] for i in range(0, len(x_train))],
                [x_train[i][1] for i in range(0, len(x_train))])


  x_test = zip([x_test[i:][0] for i in range(0, len(x_test))],
                [x_test[i][1] for i in range(0, len(x_test))])

  return x_train, x_test, y_train, y_test
x_train, x_val, y_train, y_val = split_zip(x=zipped_2, y=y_temp, test_size=0.5, random_state=42, shuffle=True)

(array([0., 0.]), array([1., 1., 1.]))


In [ ]:
y_train

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
le, ri = zip(*x_train)
print(np.array(le))
print(np.array(ri))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
from torch import nn
import torch
input_dim = 10
embedding_dim = 2
embedding = nn.Embedding(input_dim, embedding_dim)
err = False
if err:
    #Any input more than input_dim - 1, here input_dim = 10
    #Any input less than zero
    input_to_embed = torch.tensor([10])
else:
    input_to_embed = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
embed = embedding(input_to_embed)
print(embed)

tensor([[ 0.0800,  0.8640],
        [ 0.8225, -1.5877],
        [-0.3700,  0.2424],
        [ 0.1242,  1.0187],
        [-0.8652,  1.4864],
        [-0.0247,  0.9986],
        [ 0.3007,  0.9018],
        [ 1.3436, -0.1098],
        [-1.6409,  0.3632],
        [-1.7437, -1.2304]], grad_fn=<EmbeddingBackward0>)


In [ ]:
filter = torch.Tensor(np.zeros((10, 1)))
print(filter)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])


In [ ]:
feat = torch.Tensor(np.random.rand(4, 10, 3))
feat

tensor([[[0.8100, 0.9312, 0.7502],
         [0.8518, 0.4875, 0.5192],
         [0.4240, 0.1570, 0.6586],
         [0.8598, 0.2183, 0.0990],
         [0.2996, 0.4674, 0.8613],
         [0.8529, 0.3320, 0.3157],
         [0.6242, 0.7607, 0.1040],
         [0.1987, 0.1024, 0.5391],
         [0.3771, 0.8689, 0.9910],
         [0.2038, 0.9753, 0.1107]],

        [[0.1890, 0.7329, 0.8203],
         [0.5908, 0.5488, 0.4550],
         [0.1285, 0.9920, 0.4670],
         [0.1510, 0.2617, 0.6787],
         [0.1301, 0.9516, 0.6131],
         [0.7816, 0.8946, 0.8175],
         [0.2198, 0.5432, 0.1974],
         [0.5609, 0.8554, 0.2431],
         [0.4477, 0.9744, 0.6723],
         [0.0313, 0.8176, 0.3962]],

        [[0.4258, 0.6002, 0.3735],
         [0.5025, 0.4881, 0.4495],
         [0.3842, 0.2723, 0.2209],
         [0.2367, 0.6764, 0.4510],
         [0.7995, 0.5021, 0.7514],
         [0.2031, 0.6314, 0.6971],
         [0.8218, 0.8845, 0.8462],
         [0.5123, 0.1670, 0.8550],
         [0.4922

In [ ]:
filter * feat

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from category_encoders import LeaveOneOutEncoder, CatBoostEncoder, OrdinalEncoder

A = ['0', '1', '2', '3', '2']
LE_encoder = OrdinalEncoder()
train_le = LE_encoder.fit_transform(A)
print(train_le)
# test_le = LE_encoder.transform(A)

   0
0  1
1  2
2  3
3  4
4  3


In [ ]:
import numpy as np

In [ ]:
A = np.zeros((4, 5))

In [ ]:
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
A[[0, 1]]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
import pandas as pd


In [ ]:
A = [[1, 2, 3]]
temp = pd.DataFrame(data=A,  columns=['A', 'B', 'C'])
temp

A  B  C
0  1  2  3

In [ ]:
temp.reindex(['C', 'B', 'A'], axis=1)

C  B  A
0  3  2  1

In [ ]:
temp

A  B  C
0  1  2  3

In [ ]:
temp['A'][0]

1