In [ ]:
import numpy as np

In [ ]:
left = np.zeros((10, 2))
right = np.ones((10, 3))


In [ ]:
print(left)
print(right)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
zipped = zip(left, right)

In [ ]:
left_t, right_t = zip(*zipped)

In [ ]:
print(np.array(left_t))
print(np.array(right_t))


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
from torch import nn
import torch
input_dim = 10
embedding_dim = 2
embedding = nn.Embedding(input_dim, embedding_dim)
err = False
if err:
    #Any input more than input_dim - 1, here input_dim = 10
    #Any input less than zero
    input_to_embed = torch.tensor([10])
else:
    input_to_embed = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
embed = embedding(input_to_embed)
print(embed)

tensor([[-0.1420,  0.8967],
        [-0.2194, -0.4559],
        [-0.8421, -1.1855],
        [-0.8604, -1.2034],
        [ 0.4814, -1.3943],
        [-0.7740, -0.1350],
        [-1.9287,  0.7961],
        [ 0.4610,  0.5342],
        [ 0.0956,  0.9742],
        [-1.9950,  1.3485]], grad_fn=<EmbeddingBackward0>)


In [ ]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 KB 4.7 MB/s eta 0:00:00


In [ ]:
from category_encoders import LeaveOneOutEncoder, CatBoostEncoder, OrdinalEncoder

A = ['0', '1', '2', '3', '2']
LE_encoder = OrdinalEncoder()
train_le = LE_encoder.fit_transform(A)
print(train_le)
# test_le = LE_encoder.transform(A)

   0
0  1
1  2
2  3
3  4
4  3


In [ ]:
import numpy as np

In [ ]:
A = np.zeros((4, 5))

In [ ]:
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
A[[0, 1]]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
import pandas as pd


In [ ]:
A = [[1, 2, 3]]
temp = pd.DataFrame(data=A,  columns=['A', 'B', 'C'])
temp

A  B  C
0  1  2  3

In [ ]:
temp.reindex(['C', 'B', 'A'], axis=1)

C  B  A
0  3  2  1

In [ ]:
temp

A  B  C
0  1  2  3

In [ ]:
temp['A'][0]

1